# Generated by Django 3.2.3 on 2022-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='fatme', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp282', max_length=70),
        ),
    ]
