# Generated by Django 4.0.4 on 2022-05-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0034_roles_employee_user_user_role_alter_employee_emp_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp565', max_length=70),
        ),
    ]
