# Generated by Django 4.0.4 on 2022-05-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0038_alter_employee_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp498', max_length=70),
        ),
    ]
