# Generated by Django 4.0.4 on 2022-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0039_remove_employee_email_remove_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp206', max_length=70),
        ),
    ]
