# Generated by Django 4.0.4 on 2022-05-17 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0040_remove_employee_joined_remove_employee_thumb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='fatme', max_length=70)),
                ('mobile', models.CharField(max_length=15)),
                ('concrete_cube_price', models.CharField(default='00,000.00', max_length=16)),
                ('pump_opening_price', models.CharField(default='00,000.00', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp460', max_length=70),
        ),
        migrations.CreateModel(
            name='ConcreteCasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_casting', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=15)),
                ('quantity_of_concrete_cube', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.customer')),
            ],
        ),
    ]
