# Generated by Django 4.0.4 on 2022-05-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0041_customer_alter_employee_emp_id_concretecasting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='concrete_cube_price',
            field=models.IntegerField(default='00,000.00', max_length=16),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pump_opening_price',
            field=models.IntegerField(default='00,000.00', max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp240', max_length=70),
        ),
    ]
