# Generated by Django 4.0.4 on 2022-05-18 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0042_alter_customer_concrete_cube_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretecasting',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp661', max_length=70),
        ),
    ]
