# Generated by Django 4.0.4 on 2022-05-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0043_concretecasting_employee_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretecasting',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp345', max_length=70),
        ),
    ]
