# Generated by Django 4.0.4 on 2022-05-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0044_alter_concretecasting_location_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretecasting',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp428', max_length=70),
        ),
    ]
