# Generated by Django 4.0.4 on 2022-05-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0046_alter_employee_emp_id_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp630', max_length=70),
        ),
    ]
