# Generated by Django 4.0.4 on 2022-05-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0048_rename_date_creaed_expenses_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp817', max_length=70),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
