# Generated by Django 4.0.4 on 2022-05-22 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hrms.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0049_alter_employee_emp_id_alter_expenses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp542', max_length=70),
        ),
        migrations.CreateModel(
            name='EmployeeCouponPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(max_length=254, upload_to=hrms.models.employee_coupon_pdf_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
