# Generated by Django 4.0.4 on 2022-05-22 04:09

from django.db import migrations, models
import hrms.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0051_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp330', max_length=70),
        ),
        migrations.AlterField(
            model_name='employeecouponpdf',
            name='pdf_file',
            field=models.FileField(upload_to=hrms.models.employee_coupon_pdf_path),
        ),
    ]
