# Generated by Django 4.0.4 on 2022-05-24 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0053_alter_employee_emp_id_employeeadvancepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvancepayment',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp355', max_length=70),
        ),
    ]
