# Generated by Django 4.0.4 on 2022-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0055_alter_concretecasting_employee_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp206', max_length=70),
        ),
        migrations.AlterField(
            model_name='employeeadvancepayment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
