# Generated by Django 4.0.4 on 2022-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0057_alter_employee_emp_id_employeechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeechat',
            name='sender',
            field=models.CharField(choices=[('user', 'user'), ('employee', 'employee')], default='employee', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp772', max_length=70),
        ),
    ]
