# Generated by Django 4.0.5 on 2022-06-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0060_alter_employee_emp_id_alter_employeechat_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp661', max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumb',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
