# Generated by Django 4.0.5 on 2022-06-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0061_alter_employee_emp_id_alter_user_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp386', max_length=70),
        ),
    ]
